# Generated by Django 4.1.1 on 2022-10-26 19:25

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_remove_environment_team_default_true_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="function",
            name="env_variables",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.CreateModel(
            name="EnvironmentVariable",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("variable_name", models.CharField(max_length=64)),
                ("description", models.TextField(null=True)),
                ("value", models.TextField()),
                ("protect", models.BooleanField(default=False)),
                (
                    "environment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vars",
                        to="core.environment",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vars",
                        to="core.team",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="environmentvariable",
            constraint=models.UniqueConstraint(
                fields=("environment", "variable_name"),
                name="environment_variable_name_unique_together",
            ),
        ),
        migrations.AddConstraint(
            model_name="environmentvariable",
            constraint=models.UniqueConstraint(
                fields=("team", "variable_name"),
                name="team_variable_name_unique_together",
            ),
        ),
        migrations.AddConstraint(
            model_name="environmentvariable",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("environment__isnull", False), ("team__isnull", True)),
                    models.Q(("environment__isnull", True), ("team__isnull", False)),
                    _connector="OR",
                ),
                name="environment_variable_only_one_team_or_environment",
            ),
        ),
    ]
